export const T = {
    bg: "#F6F5F0",
    bgWarm: "#EFEDE6",
    card: "#FFFFFF",
    accent: "#1B3A2D",
    accentMid: "#2D5F45",
    accentLight: "#3A7D5C",
    accentPale: "#E2F0E8",
    maple: "#C41E3A",
    text: "#1C1C1A",
    textSec: "#5C5C56",
    textMut: "#9C9C94",
    success: "#1A7D46",
    successBg: "#E6F5ED",
    warn: "#B45309",
    warnBg: "#FEF7E6",
    error: "#C41E3A",
    errorBg: "#FDE8EC",
    blue: "#1E56A0",
    blueBg: "#E8F0FA",
    font: "'Source Sans 3', sans-serif",
    fontDisplay: "'Instrument Serif', Georgia, serif",
    radius: 14,
    radiusSm: 10,
};

export const S = {
    card: {
        background: T.card,
        borderRadius: T.radius,
        border: `1px solid ${T.bgWarm}`,
        padding: '28px 32px',
        marginBottom: 20,
    },
    inputBase: {
        fontFamily: T.font,
        fontSize: 15,
        padding: '10px 14px',
        borderRadius: T.radiusSm,
        border: `1.5px solid #ddd`,
        width: '100%',
        background: '#fff',
        color: T.text,
        transition: 'border-color 0.2s, box-shadow 0.2s',
    },
    btnPrimary: {
        fontFamily: T.font,
        fontSize: 16,
        fontWeight: 600,
        padding: '14px 32px',
        borderRadius: T.radius,
        border: 'none',
        background: T.accent,
        color: '#fff',
        cursor: 'pointer',
        transition: 'background 0.2s, transform 0.1s',
    },
    btnSecondary: {
        fontFamily: T.font,
        fontSize: 15,
        fontWeight: 600,
        padding: '12px 24px',
        borderRadius: T.radius,
        border: `1.5px solid ${T.accent}`,
        background: 'transparent',
        color: T.accent,
        cursor: 'pointer',
        transition: 'background 0.2s',
    },
    label: {
        fontSize: 13,
        fontWeight: 600,
        color: T.textSec,
        marginBottom: 6,
        display: 'block',
    },
    h1: {
        fontFamily: T.fontDisplay,
        fontSize: 42,
        fontWeight: 400,
        color: T.text,
        lineHeight: 1.2,
    },
    h2: {
        fontFamily: T.fontDisplay,
        fontSize: 28,
        fontWeight: 400,
        color: T.text,
        lineHeight: 1.3,
    },
    h3: {
        fontFamily: T.font,
        fontSize: 18,
        fontWeight: 600,
        color: T.text,
    },
};
